name: Frontend CI/CD

on:
  push:
    branches: [main]   

jobs:   
  test-and-push-frontend:
     runs-on: ubuntu-latest
     steps:

       - name: Checkout do código
         uses: actions/checkout@v4

       - name: Build da imagem Docker do Frontend
         run: docker build -t to-do-frontend .

       - name: Iniciar o conteiner do Frontend 
         run: docker run -d -p 8083:8083 --name frontend to-do-frontend:latest

       - name: Roda testes cypress criados
         run: docker exec frontend xvfb-run -- npm run test:e2e

       - name: Remover conteiner do Frontend
         if: always()
         run: docker stop frontend && docker rm frontend

       - name: Login to DockerHub
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
       - name: Build and Push Docker image
         uses: docker/build-push-action@v6
         with:
           context: .
           push: true
           tags: | 
             luizmario/to-do-frontend:latest
             luizmario/to-do-frontend:${{ github.sha }}
  
  
  deploy-to-ec2:
    name: Deploy to EC2 via SSH
    runs-on: ubuntu-latest
    needs: test-and-push-frontend

    steps:
      - name: Executar SSH na instância EC2 e reiniciar Docker Compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd /opt/app/
            docker compose pull
            docker compose down
            docker compose up -d
            exit
