name: Frontend CI/CD

on:
  push:
    branches: [main]   

jobs:   
  test-and-push-frontend:
     runs-on: ubuntu-latest
     steps:

       - name: Checkout do código
         uses: actions/checkout@v4

       - name: Build da imagem Docker do Frontend
         run: docker build -t to-do-frontend .

       - name: Iniciar o conteiner do Frontend 
         run: docker run -d -p 8083:8083 --name frontend to-do-frontend:latest

       - name: Instalar Cypress
         run: npm install cypress

       - name: Roda testes cypress criados
         run: npm run test:e2e -- --headless

       - name: Remover conteiner do Frontend
         if: always()
         run: docker stop frontend && docker rm frontend

       - name: Login to DockerHub
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
       - name: Build and Push Docker image
         uses: docker/build-push-action@v6
         with:
           context: .
           push: true
           tags: | 
             luizmario/to-do-frontend:latest
             luizmario/to-do-frontend:${{ github.sha }}